[profile.default]
fs_permissions = [{ access = "read-write", path = "./"}]
solc = '0.8.28'
src = 'src'
test = 'test'
out = 'out'
via_ir = true
verbosity = 3
libs = ['lib']

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
func_attrs_with_params_multiline = true
quote_style = "double"
number_underscore = "thousands"
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config